name: Continuous Integration Checks
on: [ push ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Install start-server-and-test
        run: npm install -g start-server-and-test
      - name: Start server and run tests
        run: npx start-server-and-test preview http://localhost:4173/ cy:run:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
